{{- range .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "s-%s" .name }}
type: {{ .type }}
data:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value }}
  {{- end }}
---
{{- end }}