{{- /* Base */ -}}
{{- $app := .Values.app }}
{{- $namesa := printf "sa-%s" $app }}

{{- if .Values.deployment }}
  {{- $containers := (.Values.deployment.containers | default list) -}}
  {{- if gt (len $containers) 0 }}
    {{- $ports := ((index $containers 0).ports | default list) -}}
    {{- $pname := "" -}}

    {{- /* ports pode ser lista (caso comum) ou mapa — tratamos os dois */ -}}
    {{- if (kindIs "slice" $ports) }}
      {{- if gt (len $ports) 0 }}
        {{- $pname = ((index $ports 0).name | default "") -}}
      {{- end }}
    {{- else }}
      {{- $pname = (index $ports "name" | default "") -}}
    {{- end }}

    {{- if $pname }}
      {{- $namesa = printf "sa-%s-%s" $app $pname -}}
    {{- else }}
      {{- $namesa = printf "sa-%s" $app -}}
    {{- end }}
  {{- else }}
    {{- $namesa = printf "sa-%s" $app -}}
  {{- end }}
{{- else if or .Values.daemonset .Values.statefulset }}
  {{- $namesa = printf "sa-%s" $app -}}
{{- else }}
  {{- $namesa = printf "sa-%s" $app -}}
{{- end }}

{{- $namesa = $namesa | trunc 63 | trimSuffix "-" }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $namesa | trunc 63 | trimSuffix "-" }}
  labels:
    app: {{ $app | quote }}
    component: {{ (.Values.component | default "default") | quote }}
